**Pandas (Panel Data)**

* Veri manipülasyonu ve veri analizi için yazılmış açık kaynak kodlu bir Python kütüphanesidir.
* Ekonomik ve finansal çalışmalar için doğmuştur.
* Temeli 2008 yılında atılmıştır.
* R DataFrame yapısını Python dünyasına taşımış ve DataFrame'ler üzerinde hızlı ve etkili çalışabilme imkanı sağlamıştır.
* Bir çok farklı veri tipini okuma ve yazma imkanı sağlar.

**Pandas Serisi Oluşturmak**

In [1]:
import pandas as pd

In [6]:
#İlk sutun index
pd.Series([10,82,653,524,15])

0     10
1     82
2    653
3    524
4     15
dtype: int64

In [7]:
seri=pd.Series([10,82,653,524,15])

In [8]:
type(seri)

pandas.core.series.Series

In [10]:
#İndex bilgilerine erişme
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [12]:
seri.dtype

dtype('int64')

In [13]:
seri.size

5

In [14]:
seri.ndim

1

In [23]:
seri.values

array([ 10,  82, 653, 524,  15], dtype=int64)

In [24]:
#İlk 3 değeri döndürür.Defaultu 5'tir.
seri.head(3)

0     10
1     82
2    653
dtype: int64

In [25]:
#Son 3 değeri döndürür.Defaultu 5'tir.
seri.tail(3)

2    653
3    524
4     15
dtype: int64

* İndex İsimlendirmesi

In [27]:
pd.Series([10,15,21,65,5])

0    10
1    15
2    21
3    65
4     5
dtype: int64

In [31]:
pd.Series([10,15,21,65,5],index=[1,3,5,7,9])

1    10
3    15
5    21
7    65
9     5
dtype: int64

In [32]:
pd.Series([10,15,21,65,5],index=["a","b","c","d","e"])

a    10
b    15
c    21
d    65
e     5
dtype: int64

In [33]:
seri=pd.Series([10,15,21,65,5],index=["a","b","c","d","e"])

In [35]:
seri["c"]

21

In [36]:
seri["a":"c"]

a    10
b    15
c    21
dtype: int64

* Sozlük üzerinden liste oluşturmak

In [39]:
sozluk={"reg":10,"log":11,"cart":12}

In [40]:
seri=pd.Series(sozluk)

In [42]:
seri

reg     10
log     11
cart    12
dtype: int64

In [43]:
seri["log":"cart"]

log     11
cart    12
dtype: int64

* İki seriyi birleştirerek seri oluşturma

In [44]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

Not: Seriler alt alta eklenir.

* Eleman İşlemleri

In [46]:
import numpy as np

In [50]:
a=np.array([41,24,35,47,55])
seri=pd.Series(a)
seri

0    41
1    24
2    35
3    47
4    55
dtype: int32

In [51]:
seri[0]

41

In [52]:
seri[0:3]

0    41
1    24
2    35
dtype: int32

In [56]:
 seri=pd.Series([121,200,150,99],index=["reg","loj","cart","rf"])

In [57]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [59]:
#Sadece index değerlerine erişme
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [60]:
#Sadece keys bilgilerini getirir
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [62]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [63]:
seri.values

array([121, 200, 150,  99], dtype=int64)

* Eleman sorgulama

In [65]:
#"reg" değerinin seride olup olmadığını sorgular.
"reg" in seri

True

In [67]:
"a" in seri

False

In [68]:
seri["reg"]

121

* Fancy ile eleman seçme

In [71]:
seri[["rf","reg"]]

rf      99
reg    121
dtype: int64

In [72]:
seri["reg"]=130

In [73]:
seri

reg     130
loj     200
cart    150
rf       99
dtype: int64

In [76]:
seri["reg":"loj"]

reg    130
loj    200
dtype: int64

**Pandas Dataframe**

* Pandas DataFrame Oluşturma

In [3]:
l=[1,2,39,67,95]
l

[1, 2, 39, 67, 95]

In [6]:
pd.DataFrame(l,columns=["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             95

In [11]:
import numpy as np
m=np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
pd.DataFrame(m,columns=["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [14]:
#df isimlendirme

In [15]:
df=pd.DataFrame(m,columns=["var1","var2","var3"])

In [16]:
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [18]:
df.head(1)

var1  var2  var3
0     1     2     3

In [20]:
df.columns=("deg1","deg2","deg3")

In [21]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [22]:
type(df)

pandas.core.frame.DataFrame

In [24]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [25]:
df.shape

(3, 3)

In [26]:
df.ndim

2

In [27]:
df.size

9

In [29]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
type(df.values)

numpy.ndarray

In [31]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [32]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [33]:
a=np.array([1,2,3,4,5])

In [35]:
pd.DataFrame(a,columns=["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

* Eleman İşlemleri

In [36]:
s1 =np.random.randint(10,size=5)
s2 =np.random.randint(10,size=5)
s3 =np.random.randint(10,size=5)

In [37]:
s1

array([6, 2, 5, 2, 7])

In [38]:
s2

array([3, 4, 7, 4, 2])

In [39]:
s3

array([7, 7, 3, 0, 0])

In [40]:
sozluk={"var1":s1,"var2":s2,"var3":s3}

In [41]:
sozluk

{'var1': array([6, 2, 5, 2, 7]),
 'var2': array([3, 4, 7, 4, 2]),
 'var3': array([7, 7, 3, 0, 0])}

In [42]:
df=pd.DataFrame(sozluk)

In [43]:
df

var1  var2  var3
0     6     3     7
1     2     4     7
2     5     7     3
3     2     4     0
4     7     2     0

In [44]:
df[0:1]

var1  var2  var3
0     6     3     7

In [45]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [46]:
df.index=["a","b","c","d","e"]

In [47]:
df

var1  var2  var3
a     6     3     7
b     2     4     7
c     5     7     3
d     2     4     0
e     7     2     0

In [49]:
df["c":"e"]

var1  var2  var3
c     5     7     3
d     2     4     0
e     7     2     0

In [50]:
#silme

In [64]:
df.drop("a",axis=0)

var1  var2  var3      var4
b     2     4     7  0.500000
c     5     7     3  0.714286
d     2     4     0  0.500000
e     7     2     0  3.500000

In [65]:
df

var1  var2  var3      var4
a     6     3     7  2.000000
b     2     4     7  0.500000
c     5     7     3  0.714286
d     2     4     0  0.500000
e     7     2     0  3.500000

In [66]:
l=["var1","var5","var2"]

In [67]:
for i in l:
    print(i in df)

True
False
True


In [68]:
df["var1"]

a    6
b    2
c    5
d    2
e    7
Name: var1, dtype: int32

In [61]:
df["var4"]=df["var1"] / df["var2"]
df

var1  var2  var3      var4
a     6     3     7  2.000000
b     2     4     7  0.500000
c     5     7     3  0.714286
d     2     4     0  0.500000
e     7     2     0  3.500000

In [70]:
#degisken silmek
df.drop("var4",axis=1)

var1  var2  var3
a     6     3     7
b     2     4     7
c     5     7     3
d     2     4     0
e     7     2     0

In [71]:
df

var1  var2  var3      var4
a     6     3     7  2.000000
b     2     4     7  0.500000
c     5     7     3  0.714286
d     2     4     0  0.500000
e     7     2     0  3.500000

In [72]:
df.drop("var4",axis=1,inplace=True)

In [73]:
df

var1  var2  var3
a     6     3     7
b     2     4     7
c     5     7     3
d     2     4     0
e     7     2     0

In [75]:
l=["var1","var2"]

In [76]:
df.drop(l,axis=1)

var3
a     7
b     7
c     3
d     0
e     0

* Gözlem ve Değişken Seçimi: loc & iloc

In [77]:
m=np.random.randint(1,30,size=(10,3))
df=pd.DataFrame(m,columns=["var1","var2","var3"])
df

var1  var2  var3
0    29    10     9
1     9    19    28
2    22    28    28
3     2     6     3
4     3    19    22
5     1    19    21
6    19    17    13
7    18     8     8
8    23     3    26
9    28     3    13

In [78]:
#loc: Tanımlandığı şekli ile seçim yapmak için kullanılır.

In [80]:
df.loc[0:3]

var1  var2  var3
0    29    10     9
1     9    19    28
2    22    28    28
3     2     6     3

In [81]:
#iloc: Alışık olduğumuz indexleme mantığı ile seçim yapar.

In [82]:
df.iloc[0:3]

var1  var2  var3
0    29    10     9
1     9    19    28
2    22    28    28

In [84]:
df.iloc[0,0]

29

In [87]:
df.iloc[:3,:2]

var1  var2
0    29    10
1     9    19
2    22    28

In [88]:
df.loc[0:3,"var3"]

0     9
1    28
2    28
3     3
Name: var3, dtype: int32

In [92]:
df.iloc[0:3]["var3"]

0     9
1    28
2    28
Name: var3, dtype: int32

* Koşullu Eleman İşlemleri

In [3]:
import numpy as np
import pandas as pd

In [8]:
m= np.random.randint(1,30,size=(10,3))
df=pd.DataFrame(m,columns=["var1","var2","var3"])
df

var1  var2  var3
0    16    24     9
1    20    10    21
2    23    13    27
3    21    13    29
4     2     1    28
5     8     5    10
6     7    14    10
7     1    29     9
8    25    16    15
9     3     9    11

In [10]:
df[0:2]

var1  var2  var3
0    16    24     9
1    20    10    21

In [14]:
df[df.var1>15]["var1"]

0    16
1    20
2    23
3    21
8    25
Name: var1, dtype: int32

In [22]:
df[(df.var1 > 15) & (df.var3<15)]

var1  var2  var3
0    16    24     9

In [24]:
df.loc[(df.var1 > 15),["var1","var2" ]]

var1  var2
0    16    24
1    20    10
2    23    13
3    21    13
8    25    16

In [26]:
df[(df.var1 > 15)][["var1","var2" ]]

var1  var2
0    16    24
1    20    10
2    23    13
3    21    13
8    25    16

* Birleştirme (Join) İşlemleri

In [30]:
a= np.random.randint(1,30,size=(5,3))
df1=pd.DataFrame(a,columns=["var1","var2","var3"])
df1

var1  var2  var3
0     8    14     5
1    16     4    28
2    21    23     9
3    20    23     5
4    13    26    14

In [31]:
df2=df1 + 99

In [32]:
df2

var1  var2  var3
0   107   113   104
1   115   103   127
2   120   122   108
3   119   122   104
4   112   125   113

In [35]:
#Alt alta birleştirir
pd.concat([df1,df2])

var1  var2  var3
0     8    14     5
1    16     4    28
2    21    23     9
3    20    23     5
4    13    26    14
0   107   113   104
1   115   103   127
2   120   122   108
3   119   122   104
4   112   125   113

In [36]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
  

In [37]:
pd.concat([df1,df2],ignore_index=True)

var1  var2  var3
0     8    14     5
1    16     4    28
2    21    23     9
3    20    23     5
4    13    26    14
5   107   113   104
6   115   103   127
7   120   122   108
8   119   122   104
9   112   125   113

In [39]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [41]:
df2.columns=["var1","var2","deg3"]

In [42]:
df2

var1  var2  deg3
0   107   113   104
1   115   103   127
2   120   122   108
3   119   122   104
4   112   125   113

In [43]:
df1

var1  var2  var3
0     8    14     5
1    16     4    28
2    21    23     9
3    20    23     5
4    13    26    14

In [44]:
pd.concat([df1,df2])

var1  var2  var3   deg3
0     8    14   5.0    NaN
1    16     4  28.0    NaN
2    21    23   9.0    NaN
3    20    23   5.0    NaN
4    13    26  14.0    NaN
0   107   113   NaN  104.0
1   115   103   NaN  127.0
2   120   122   NaN  108.0
3   119   122   NaN  104.0
4   112   125   NaN  113.0

In [53]:
#Kesişimlerine göre birleştirir (innner)
pd.concat([df1,df2],join="inner",ignore_index="True")

var1  var2
0     8    14
1    16     4
2    21    23
3    20    23
4    13    26
5   107   113
6   115   103
7   120   122
8   119   122
9   112   125

In [56]:
#birebir birleştirme

In [57]:
dfa=pd.DataFrame({'calisanlar':['Ali','Veli','Ayse','Fatma'],
                  'grup':['Muhasebe','Muhendislik','Muhendislik','İK']})
dfa

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [63]:
dfb=pd.DataFrame({'calisanlar':['Ayse','Ali','Veli','Fatma'],
                  'ilk_giris':[2010,2009,2014,2019]})
dfb

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [64]:
pd.merge(dfa,dfb)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [65]:
pd.merge(dfa,dfb,on="calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [66]:
#coktan teke birleştirme (many to one)

In [69]:
dfc=pd.merge(dfa,dfb)

In [70]:
dfc


calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [73]:
dfd=pd.DataFrame({'grup':['Muhasebe','Muhendislik','İK'],
                  'mudur':['Caner','Mustafa','Berkcan']})
dfd

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [75]:
pd.merge(dfc,dfd)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [76]:
#coktan coka birleştirme (many to many)

In [78]:
dfe=pd.DataFrame({'grup':['Muhasebe','Muhasebe','Muhendislik','Muhendislik','İK','İK'],
                 'yetenekler':['matematik','excel','kodlama','linux','excel','yonetim']})
dfe

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [79]:
dfa

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [82]:
pd.merge(dfa,dfe)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

**Gruplama ve Toplulaştırma İşlemleri**

* Toplulaştırma ve Gruplama (Aggregation & Grouping)

Basit toplulaştırma fonksiyonları:
* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [87]:
import seaborn as sns

In [91]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [92]:
#seaborn kütüphanesinden planets verisetini yüklüyoruz.
df = sns.load_dataset("planets")

In [97]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [98]:
df.shape

(1035, 6)

In [101]:
df.select_dtypes(include=['number']).mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [102]:
#Ortalama
df["mass"].mean()

2.6381605847953216

In [106]:
#Değerleri sayar
df["mass"].count()

513

In [107]:
#Minimum değer
df["mass"].min()

0.0036

In [108]:
#Maximum değer
df["mass"].max()

25.0

In [109]:
#Toplamı
df["mass"].sum()

1353.37638

In [111]:
#Standart sapma
df["mass"].std()

3.8186166509616046

In [113]:
#Varyans
df["mass"].var()

14.58183312700122

In [117]:
#Bütün değişkenlerin betimsel istatistiklerini gösterir.
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [118]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [120]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

In [122]:
#Eksik değerleri silip gözlemler.
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

* Gruplama İşlemleri

In [129]:
df=pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                'veri':[10,11,52,23,43,55]}, columns=['gruplar','veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

Gruplama işlemi verisetinde yer alan kategorik değişkenlerin gruplarının yakalanması ve bu grupların özelinde bazı işlemler yapılmasıdır.

In [130]:
#burada grupları yakalıyor.
df.groupby("gruplar")

In [132]:
#burada grupların ortalamasını alıyoruz.
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [133]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [139]:
dfab=sns.load_dataset("planets")
dfab.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [147]:
dfab.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [148]:
dfab.groupby("method")["mass"].mean()

method
Astrometry                            NaN
Eclipse Timing Variations        5.125000
Imaging                               NaN
Microlensing                          NaN
Orbital Brightness Modulation         NaN
Pulsar Timing                         NaN
Pulsation Timing Variations           NaN
Radial Velocity                  2.630699
Transit                          1.470000
Transit Timing Variations             NaN
Name: mass, dtype: float64

In [149]:
dfab.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

**İleri Toplulaştırma İşlemleri (Aggregate, filter, transform, apply)**

In [5]:
import pandas as pd
import numpy as np
df =pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                 'degisken1':[10,23,33,22,11,99],
                 'degisken2':[100,253,333,262,111,969]},columns=['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

* Aggregate

In [6]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [12]:
df.groupby("gruplar").aggregate(["min","median","max"])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [13]:
df.groupby("gruplar").aggregate({'degisken1':"min","degisken2":"max"})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

* Filter

In [14]:
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [18]:
def filter_func(x):
    return x["degisken1"].std() > 9
    

In [20]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [19]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

* Transform

In [21]:
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [24]:
df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [30]:
df_a=df.iloc[:,1:3]
df_a

degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [34]:
#Transform sütun bazında çalışır.
df_a.transform(lambda x: (x-x.mean())/x.std())

degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

* Apply

In [40]:
df =pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                 'degisken1':[10,23,33,22,11,99],
                 'degisken2':[100,253,333,262,111,969]},columns=['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [47]:
df.apply("sum")

gruplar      ABCABC
degisken1       198
degisken2      2028
dtype: object

In [48]:
df.groupby("gruplar").apply("sum")

degisken1  degisken2
gruplar                      
A               32        362
B               34        364
C              132       1302

In [49]:
df.groupby("gruplar").apply("mean")

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

**Pivot Tablolar**

Veri setleri üzerinde bazı satır ve sütun işlemleri yaoarak veri setini amaca uygun hale
getirmek için kullanılan yapılardır.
(Groupby ın çok boyutlu versiyonu olarak düşünülebilir.)

In [55]:
import numpy as np
import pandas as pd
import seaborn as sns

In [56]:
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [58]:
#Cinsiyete(sex) göre veriyi gruplayıp sağ kalma(survived) durumlarını inceliyoruz.
titanic.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [73]:
titanic.groupby(["sex","class"], observed=False)[["survived"]].aggregate("mean")

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [74]:
titanic.groupby(["sex","class"], observed=False)[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [77]:
#Pivot ile table
titanic.pivot_table("survived",index="sex",columns="class", observed=False)

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [78]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [82]:
age=pd.cut(titanic["age"],[0,18,90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [84]:
titanic.pivot_table("survived",["sex",age],"class",observed=False)

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

**Dış Kaynaklı Veri Okuma**

In [18]:
import pandas as pd

In [10]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: '

In [4]:
pd.read_csv("reading_data/ornekcsv.csv")

a;b;c
0    78;12;1
1    78;12;2
2   78;324;3
3      7;2;4
4    88;23;5
5       6;2;
6    56;11;6
7     7;12;7
8    56;21;7
9    346;2;8
10     5;1;8
11  456;21;8
12   3;12;88

In [6]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv",sep=";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [25]:
#txt okuma
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [26]:
#xlsx okuma
pd.read_excel("reading_data/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [27]:
df=pd.read_excel("reading_data/ornekx.xlsx")

In [29]:
type(df)

pandas.core.frame.DataFrame

In [30]:
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [32]:
df.columns=("A","B","C")

In [33]:
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0