**Numpy**
(Numerical Python)

-Bilimsel hesaplamalar için kullanılır.

-Arrayler/çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.

-Temelleri 1995'te (matrix-sig, Guido Van Rossum) atılmış nihai olarak 2005(Travis Oliphant) yılında hayata geçmiştir.

-Listelere benzerdir,farkı;verimli veri saklama ve vektöre operasyonlardır.

In [8]:
import numpy as np

In [13]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [14]:
a*b

array([ 2,  6, 12, 20])

**Numpy Array'i Oluşturmak**

In [20]:
c= np.array([1,2,3,4,5])
c

array([1, 2, 3, 4, 5])

In [19]:
type(c)

numpy.ndarray

In [25]:
np.array([1.5,2,3,4,5], dtype="int")


array([1, 2, 3, 4, 5])

In [26]:
#Sıfırdan array oluşturma

In [27]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones((3,5),dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [32]:
np.arange(0,32,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [33]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [35]:
np.random.normal(10,4,(3,4))

array([[11.73650462, 16.06542256, 13.46633454, 11.28184989],
       [-1.77866123, 15.4024638 ,  2.55532543,  8.51819826],
       [15.00867844,  4.31014935,  6.39674103,  8.68213841]])

In [38]:
np.random.randint(0,10,(3,3))

array([[1, 6, 4],
       [2, 5, 8],
       [8, 0, 3]])

**Özellikleri**
* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [39]:
np.random.randint(10,size=10)

array([2, 6, 3, 8, 9, 1, 7, 6, 2, 2])

In [40]:
a=np.random.randint(10,size=10)

In [41]:
a.ndim

1

In [42]:
a.shape

(10,)

In [43]:
a.size

10

In [44]:
a.dtype

dtype('int32')

In [45]:
b= np.random.randint(10,size=(3,5))

In [47]:
b

array([[4, 8, 3, 4, 9],
       [4, 6, 8, 6, 4],
       [5, 1, 1, 1, 0]])

In [48]:
b.ndim

2

In [49]:
b.shape

(3, 5)

In [50]:
b.size

15

In [51]:
b.dtype

dtype('int32')

**Yeniden Şekillendirme (reshaping)**

In [53]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
a= np.arange(1,10)

In [56]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a.ndim

1

In [59]:
b=a.reshape((1,9))

In [60]:
b.ndim

2

**Array Birlestirme (Concatenation)**

In [61]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [63]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [64]:
z=np.array([7,8,9])

In [65]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

* İki Boyut

In [66]:
a=np.array([[1,2,3],[4,5,6]])

In [68]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])