**Numpy**
(Numerical Python)

-Bilimsel hesaplamalar için kullanılır.

-Arrayler/çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.

-Temelleri 1995'te (matrix-sig, Guido Van Rossum) atılmış nihai olarak 2005(Travis Oliphant) yılında hayata geçmiştir.

-Listelere benzerdir,farkı;verimli veri saklama ve vektöre operasyonlardır.

In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [14]:
a*b

array([ 2,  6, 12, 20])

**Numpy Array'i Oluşturmak**

In [20]:
c= np.array([1,2,3,4,5])
c

array([1, 2, 3, 4, 5])

In [19]:
type(c)

numpy.ndarray

In [25]:
np.array([1.5,2,3,4,5], dtype="int")


array([1, 2, 3, 4, 5])

In [26]:
#Sıfırdan array oluşturma

In [27]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones((3,5),dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [32]:
np.arange(0,32,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [33]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [35]:
np.random.normal(10,4,(3,4))

array([[11.73650462, 16.06542256, 13.46633454, 11.28184989],
       [-1.77866123, 15.4024638 ,  2.55532543,  8.51819826],
       [15.00867844,  4.31014935,  6.39674103,  8.68213841]])

In [38]:
np.random.randint(0,10,(3,3))

array([[1, 6, 4],
       [2, 5, 8],
       [8, 0, 3]])

**Özellikleri**
* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [39]:
np.random.randint(10,size=10)

array([2, 6, 3, 8, 9, 1, 7, 6, 2, 2])

In [40]:
a=np.random.randint(10,size=10)

In [41]:
a.ndim

1

In [42]:
a.shape

(10,)

In [43]:
a.size

10

In [44]:
a.dtype

dtype('int32')

In [45]:
b= np.random.randint(10,size=(3,5))

In [47]:
b

array([[4, 8, 3, 4, 9],
       [4, 6, 8, 6, 4],
       [5, 1, 1, 1, 0]])

In [48]:
b.ndim

2

In [49]:
b.shape

(3, 5)

In [50]:
b.size

15

In [51]:
b.dtype

dtype('int32')

**Yeniden Şekillendirme (reshaping)**

In [53]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
a= np.arange(1,10)

In [56]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a.ndim

1

In [59]:
b=a.reshape((1,9))

In [60]:
b.ndim

2

**Array Birlestirme (Concatenation)**

In [61]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [63]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [64]:
z=np.array([7,8,9])

In [65]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

* İki Boyut

In [66]:
a=np.array([[1,2,3],[4,5,6]])

Satır bazında birleştirme

In [71]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Sütun bazında birleştirme

In [72]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Array Ayırma (Splittig)**

In [4]:
x=np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [5]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [6]:
a,b,c=np.split(x,[3,5])

In [7]:
a

array([1, 2, 3])

In [8]:
b

array([99, 99])

In [9]:
c

array([3, 2, 1])

* iki boyutlu ayırma

In [12]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [14]:
ust,alt=np.vsplit(m,[2])

In [15]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [21]:
sag,sol=np.hsplit(m,[2])

In [22]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [23]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

**Sıralama (Sorting)**

In [30]:
v=np.array([2,1,4,5,3])


In [25]:
v

array([2, 1, 4, 5, 3])

In [31]:
np.sort(v)
#Numpyın içerisinden çağırıldığında veri setinin orjinal yapısını bozmaz.

array([1, 2, 3, 4, 5])

In [32]:
v.sort()
#Veri setinin yapısını kalıcı olarak değiştirir.

In [28]:
v

array([1, 2, 3, 4, 5])

* İki boyutlu array sıralama

In [34]:
m=np.random.normal(20,5,(3,3))
#np.random.normal(Ortalama,Standart Sapma,Array boyutu)

In [35]:
m

array([[21.25132576, 22.79917176, 19.30462208],
       [18.74293778, 26.38198374, 13.94354321],
       [17.38131012, 18.75260747, 21.50891312]])

In [36]:
#Satırları sıralama
np.sort(m,axis=1)

array([[19.30462208, 21.25132576, 22.79917176],
       [13.94354321, 18.74293778, 26.38198374],
       [17.38131012, 18.75260747, 21.50891312]])

In [37]:
#Sütunları sıralama
np.sort(m,axis=0)

array([[17.38131012, 18.75260747, 13.94354321],
       [18.74293778, 22.79917176, 19.30462208],
       [21.25132576, 26.38198374, 21.50891312]])

**Index ile Elemanlara Erişmek**

In [39]:
a=np.random.randint(10,size=10)
a

array([6, 4, 5, 8, 2, 7, 9, 8, 2, 3])

In [44]:
a[0] 

100

In [41]:
a[-1]

3

In [42]:
a[0]=100

In [43]:
a

array([100,   4,   5,   8,   2,   7,   9,   8,   2,   3])

In [46]:
m=np.random.randint(10,size=(3,5))
m

array([[2, 9, 0, 5, 0],
       [9, 4, 0, 5, 5],
       [2, 3, 0, 7, 0]])

In [48]:
m[0,0]

2

In [49]:
m[1,1]

4

In [51]:
m[2,3]

7

In [52]:
m[1,3]=99

m

In [54]:
m[2,4]=2.2

In [57]:
m
#Arrayın tipi int olduğu için float değerin tam kısmını alır.

array([[ 2,  9,  0,  5,  0],
       [ 9,  4,  0, 99,  5],
       [ 2,  3,  0,  7,  2]])

Not:İçerisinde oluşturma esnasında sadece 1 tane ondalıklı değer varsa bütün arrayin tipini
ondalıklı olarak görür. Fakat var olan değere dışarıdan Array dışı farklı bir tiple ekleme yapmaya çalıştığımızda Arrayin tipi geçerli olur.

**Array Alt Küme İşlemleri**

* Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [64]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [61]:
a[0:3]

array([20, 21, 22])

In [62]:
a[:3]

array([20, 21, 22])

In [63]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [65]:
a[1::2]

array([21, 23, 25, 27, 29])

In [66]:
a[0::2]

array([20, 22, 24, 26, 28])

* İki boyutlu slice işlemleri

In [67]:
m=np.random.randint(10,size=(5,5))

In [69]:
m

array([[2, 9, 3, 6, 6],
       [3, 8, 3, 2, 1],
       [3, 5, 8, 0, 0],
       [8, 2, 9, 6, 3],
       [2, 0, 1, 7, 2]])

In [73]:
#m[Satır:,Sütun]
m[:,0]

array([2, 3, 3, 8, 2])

In [72]:
m[:,1]

array([9, 8, 5, 2, 0])

In [74]:
m[0,:]

array([2, 9, 3, 6, 6])

In [75]:
m[1,:]

array([3, 8, 3, 2, 1])

In [77]:
#0 dan 2 ye kadar satırlar.
#0 dan 3 e kadar sütunlar.
m[0:2,0:3]

array([[2, 9, 3],
       [3, 8, 3]])

In [79]:
m[:,0:2]

array([[2, 9],
       [3, 8],
       [3, 5],
       [8, 2],
       [2, 0]])

In [80]:
m[1:3,0:2]

array([[3, 8],
       [3, 5]])

Arraylarin alt kümelerinde işlem yapıp kaydettiğimizde sonradan değişiklik yaparsak ilk halindede değişim olur yani referans tipinde tutar. Aşağıda örnekleri verilmiştir.

In [91]:
a=np.random.randint(10,size=(5,5))
a

array([[5, 8, 2, 0, 9],
       [5, 4, 5, 4, 6],
       [8, 1, 1, 4, 0],
       [4, 6, 7, 9, 2],
       [6, 2, 9, 5, 6]])

In [92]:
alt_a=a[0:3,0:2]
alt_a


array([[5, 8],
       [5, 4],
       [8, 1]])

In [93]:
alt_a[0,0]=999

In [94]:
alt_a[1,1]=888

In [95]:
alt_a

array([[999,   8],
       [  5, 888],
       [  8,   1]])

In [96]:
a

array([[999,   8,   2,   0,   9],
       [  5, 888,   5,   4,   6],
       [  8,   1,   1,   4,   0],
       [  4,   6,   7,   9,   2],
       [  6,   2,   9,   5,   6]])

**Alt Küme Üzerinde İşlem Yapmak**

Alt kümeye özel işlemler yapmak istediğimizde (Yani hem ilk durumu korumak istiyoruz hemde alt kümeye özel işlem yapmak istiyoruz.)
bu yöntemleri kullanabiliriz.--->copy()
 

In [100]:
m=np.random.randint(10,size=(5,5))
m

array([[1, 3, 3, 7, 9],
       [6, 6, 0, 1, 1],
       [6, 0, 7, 6, 0],
       [4, 0, 3, 3, 1],
       [4, 7, 6, 3, 7]])

In [103]:
alt_m=m[0:3,0:2].copy()
alt_m

array([[1, 3],
       [6, 6],
       [6, 0]])

In [106]:
alt_m[0,0]=999

In [107]:
alt_m

array([[999,   3],
       [  6,   6],
       [  6,   0]])

In [108]:
m

array([[1, 3, 3, 7, 9],
       [6, 6, 0, 1, 1],
       [6, 0, 7, 6, 0],
       [4, 0, 3, 3, 1],
       [4, 7, 6, 3, 7]])